
[env]
TERM = "xterm-256color"

[window]
startup_mode = "SimpleFullscreen"
padding.x = 10
padding.y = 10

decorations = "Buttonless"
opacity = 0.8
blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGMDZ Nerd Font Mono"
size = 12

[general]
import = [
  "~/.config/alacritty/theme/themes/tokyo-night-storm.toml"
]

